<a href="https://colab.research.google.com/github/bgkoro/datamining/blob/main/DataMiningPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('roti2.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['Minggu' 23.0 299000.0]
 ['Senin' 22.0 291000.0]
 ['Selasa' 19.0 247000.0]
 ['Rabu' nan 195000.0]
 ['Kamis' 16.0 215000.0]
 ['Jumat' 27.0 nan]]


In [ ]:
print(y)

['Cerah' 'Cerah' 'Hujan' 'Hujan' 'Hujan' 'Cerah']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['Minggu' 23.0 299000.0]
 ['Senin' 22.0 291000.0]
 ['Selasa' 19.0 247000.0]
 ['Rabu' 21.4 195000.0]
 ['Kamis' 16.0 215000.0]
 ['Jumat' 27.0 249400.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[0.0 0.0 1.0 0.0 0.0 0.0 23.0 299000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 22.0 291000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 19.0 247000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 21.4 195000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 16.0 215000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 27.0 249400.0]]


In [ ]:
print(y)

['Cerah' 'Cerah' 'Hujan' 'Hujan' 'Hujan' 'Cerah']


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 0 1 1 1 0]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [ ]:
print(x_train)

[[0.0 1.0 0.0 0.0 0.0 0.0 16.0 215000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 23.0 299000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 21.4 195000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 27.0 249400.0]]


In [ ]:
print(x_test)

[[0.0 0.0 0.0 0.0 1.0 0.0 19.0 247000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 22.0 291000.0]]


In [ ]:
print(y_train)

[1 0 1 0]


In [ ]:
print(y_test)

[1 0]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[0.0 1.0 0.0 -0.5773502691896258 0.0 0.0 -1.4826765843777983
  -0.6238994478339747]
 [0.0 0.0 1.0 -0.5773502691896258 0.0 0.0 0.2914663370999086
  1.5064889106235]
 [0.0 0.0 0.0 1.7320508075688774 0.0 0.0 -0.11405204495213901
  -1.1311347712762305]
 [1.0 0.0 0.0 -0.5773502691896258 0.0 0.0 1.3052622922300268
  0.24854530848670536]]


In [ ]:
print(x_test)

[[0.0 0.0 0.0 -0.5773502691896258 1.0 0.0 -0.7223296180302096
  0.18767706967363468]
 [0.0 0.0 0.0 -0.5773502691896258 0.0 1.0 0.038017348317379074
  1.3035947812465976]]
